theme: jekyll-theme-slate
title: Bixal UX Design Team Handbook
description: Practices and expectations of UX designers and researchers at Bixal

baseurl: "https://bixal.github.io/bixal-uxd-team-handbook"
